# Main Page Setup
title: Sammy Tribble's Portfolio | Hello, world! # This is what shows up in the tab of the browser


# Hero Section
name: Sammy Tribble
headline: I am a test bed engineer.
description: >- # dont remove this line. this will ignore all new lines until the next section
  I am an aerospace robotics student at Harvey Mudd College passionate about autonomous navigation and space exploration. I enjoy designing rover test beds and experiments that evaluate autonomous navigation tasks, like identifying sources of localization error or performing image segmentation. I'm researching Mars-Analog environments and I'm designing a high-fidelity simulation tool for Mars rovers with the Unreal Engine, which addresses the sim-to-real gap: the ability of modern simulation tools to emulate realism between robotics sensor inputs and feedback. 

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpg

# Link your resume
resume: ./assets/resume/Resume.pdf

# Set up external links - this will show up as small icons next to your name.
external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: samuel-tribble-a5071328b    # https://www.linkedin.com/in/samuel-tribble-a5071328b/
  github: sammyt07    # https://github.com/sammyt07/

# Publications Section - this shows my research work.
publications:
- title: "Synthetic Martian Terrain Generation Using Adaptive Diffusion Models" 
  url: https://www.sciencedirect.com/science/article/pii/S1877050925025402


# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Software Engineering
    tools:
    - VS Code
    - Jupyter Notebook
    - Git/GitHub
    - C++
    - Python
    - Linux (Ubuntu 20.04)
  - category: Robotics
    tools:
    - ROS 2 (foxy/humble)
    - 3D Printing
    - NVIDIA Jetbot-mini
    - ROBOTIS TurtleBot
    - Arduino / Raspberry Pi / NVIDIA Jetson Nano
    - Breadboarding for circuit testing
  - category: 3D Simulation
    tools:
    - Blender (low-fidelity primitives and animations)
    - Gazebo
    - Unreal Engine
    - Godot
    - Unity

# Add personal email for contact.
contact:
- email: sammy.l.tribble@gmail.com


# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#d1f0ff"
  light_background: "#f3f5fb"




#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
